---
title: "Assessing the Impact of Batch Effect Associated Missing Values on Functional Analysis in High-Throughput Biomedical Data"
author: "Harvard Wai Hann Hui"
date: "2024-10-18"
output: html_document
---

```{r setup, include=FALSE, set.seed(123456)}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = T)
```

Load the libraries
```{r}
library(corrplot)
library(gtools)
library(ggplot2)
library(ggfortify)
library(mice)
library(sva)
library(vegan)
library(imputeLCMD)
library(limma)
library(reshape2)
library(missForest)
library(ggrepel)
library(dplyr)
library(grid)
library(gridExtra)
library(pROC)
library(ggpubr)
library(pheatmap)
library(visdat)
library(magrittr)
library(MESS)
library(mvdalab)
library(ggplotify)
library(purrr)
library(rstatix)
library(here)
wd <- here()
source(paste0(wd, "/BEAMs/functions.r"))
```

Load the data
```{r}
#### Set seed for reproducibility
set.seed(123456)

#### Load the data
LTQO65 <- read.table(file=paste0(wd,"/BEAMs/CPTAC/LTQO65/combined_peptide.tsv"), sep='\t', header=TRUE)
LTQO65 <- LTQO65[-which(grepl('contam',LTQO65$Protein)),]

LTQP65 <- read.table(file=paste0(wd,"/BEAMs/CPTAC/LTQP65/combined_peptide.tsv"), sep='\t', header=TRUE)
LTQP65 <- LTQP65[-which(grepl('contam',LTQP65$Protein)),]

LTQW56 <- read.table(file=paste0(wd,"/BEAMs/CPTAC/LTQW56/combined_peptide.tsv"), sep='\t', header=TRUE)
LTQW56 <- LTQW56[-which(grepl('contam',LTQW56$Protein)),]

LTQ86 <- read.table(file=paste0(wd,"/BEAMs/CPTAC/LTQ86/combined_peptide.tsv"), sep='\t', header=TRUE)
LTQ86 <- LTQ86[-which(grepl('contam',LTQ86$Protein)),]

#### Extract intensity columns
exprs.LTQO65 <- LTQO65[,which(grepl('MaxLFQ.Intensity', colnames(LTQO65)))]
rownames(exprs.LTQO65) <- LTQO65$Peptide.Sequence
colnames(exprs.LTQO65) <- paste0('LTQO65_',colnames(exprs.LTQO65))

exprs.LTQP65 <- LTQP65[,which(grepl('MaxLFQ.Intensity', colnames(LTQP65)))]
rownames(exprs.LTQP65) <- LTQP65$Peptide.Sequence
colnames(exprs.LTQP65) <- paste0('LTQP65_',colnames(exprs.LTQP65))

exprs.LTQW56 <- LTQW56[,which(grepl('MaxLFQ.Intensity', colnames(LTQW56)))]
rownames(exprs.LTQW56) <- LTQW56$Peptide.Sequence
colnames(exprs.LTQW56) <- paste0('LTQW56_',colnames(exprs.LTQW56))

exprs.LTQ86 <- LTQ86[,which(grepl('MaxLFQ.Intensity', colnames(LTQ86)))]
rownames(exprs.LTQ86) <- LTQ86$Peptide.Sequence
colnames(exprs.LTQ86) <- paste0('LTQ86_',colnames(exprs.LTQ86))

proteins = unique(c(LTQO65$Protein, LTQP65$Protein, LTQW56$Protein, LTQ86$Protein))
peptides = unique(c(LTQO65$Peptide.Sequence, LTQP65$Peptide.Sequence, LTQW56$Peptide.Sequence, LTQ86$Peptide.Sequence))

#### Combine the matrices
matrix <- exprs.LTQO65
matrix$peptide <- rownames(matrix)

add_peps <- setdiff(peptides, rownames(matrix))
add_matrx <- matrix(data=NA, nrow=length(add_peps), ncol=15)
add_matrx <- as.matrix(cbind(add_matrx, add_peps))
rownames(add_matrx) <- add_peps
colnames(add_matrx) <- colnames(matrix)
matrix1 <- rbind(matrix, add_matrx)

matrix2 <- exprs.LTQP65
matrix2$peptide <- rownames(matrix2)
matrix3 <- exprs.LTQW56
matrix3$peptide <- rownames(matrix3)
matrix4 <- exprs.LTQ86
matrix4$peptide <- rownames(matrix4)

h <- list()
g <- list()
f <- list()
d <- list()
h[[1]] <- as_tibble(matrix1)
g[[1]] <- as_tibble(matrix2)
f[[1]] <- as_tibble(matrix3)
d[[1]] <- as_tibble(matrix4)

combined1 <- map2(h, g, left_join)
combined2 <- map2(combined1, f, left_join)
combined3 <- map2(combined2, d, left_join)

exprs = as.data.frame(combined3[[1]][,c(1:15,17:61)])
rownames(exprs) <- combined3[[1]]$peptide
exprs[exprs == 0] <- NA

vis_miss(exprs)

# create feature information
featuredata = rbind(LTQ86,LTQO65,LTQP65,LTQW56)
featuredata = cbind(peptide=featuredata$Peptide.Sequence, protein=featuredata$Protein)
rownames(featuredata) = featuredata[,1]

# get unique peptides only
featuredata = featuredata[unique(featuredata[,1]),]
featuredata = as.data.frame(featuredata) %>% mutate(protein=as.factor(protein))
# reorder peptides to match exprs rows
reorder_featuredata = match(rownames(exprs), featuredata[,1])
featuredata = featuredata[reorder_featuredata,]

# Determine number of peptides identifying each protein
sel <- as.data.frame(featuredata) %>% group_by(protein) %>% mutate(identified = n())
pep_per_prot <- as.matrix(sel[,2:3]) %>% set_rownames(.[,1])
unique_pep_per_prot <- unique(pep_per_prot[,1])
pep_per_prot <- as.data.frame(pep_per_prot[unique_pep_per_prot,]) %>% mutate(identified=as.numeric(.[,2]))

# Apply log2 transformation
log_exprs = log2(apply(exprs, 2, as.numeric))

# Set the meta data
batch_factor = rep(c(1,2,3,4), each=15)
class_factor = rep(rep(c(1,2,3,4,5), each=3),4)
pdat = data.frame(batch=batch_factor, class=class_factor)

# Class-specific quantile normalization
exprs_norm = quantileNormByClass(log_exprs, as.factor(class_factor))

# Aggregate peptide intensities to protein level
protein_exprs <- aggregate_protein_expression(exprs_norm,featuredata, log=FALSE)
order_proteins <- match(pep_per_prot$protein, rownames(protein_exprs))
protein_exprs <- protein_exprs[order_proteins,] %>% set_colnames(.,colnames(exprs))

```

Impute missing values
```{r}
nsamples = ncol(protein_exprs)
nbatches = length(unique(batch_factor))
batch_samples = nsamples/nbatches

# Remove features with too many missing values
cptac_df = filter.mvs(protein_exprs, (nsamples-batch_samples)/nsamples)
dim(cptac_df)
vis_miss(as.data.frame(cptac_df)) + theme(axis.text.x = element_blank())

# Perform missing value imputation
KNN_cptac = do.knn(cptac_df, k=floor(sqrt(nsamples/2)))
MinProb_cptac = impute.MinProb(cptac_df, tune.sigma = 0.5)
Mean_cptac = mean.imp(cptac_df)
SVD_cptac = t(impute.wrapper.SVD(t(cptac_df), K=3))
```

Correct batch effect by ComBat
```{r}
CPTAC_list = list(Original=cptac_df, KNN=KNN_cptac, MinProb=MinProb_cptac, Mean=Mean_cptac, SVD=SVD_cptac)

ComBat_CPTAC_list = lapply(CPTAC_list[2:length(CPTAC_list)], function(x) do.combat.sim(x, pdat, cov=F))

ComBat_CPTAC_hist = data.frame(lapply(ComBat_CPTAC_list, function(x) as.numeric(x)))%>% melt()
```
Create PCA plot data
```{r, fig.width=10, fig.height=5.5}
#### Obtain complete CPTAC data
complete <- na.omit(cptac_df)
CPTAC_list2 <- CPTAC_list
CPTAC_list2[["Original"]] <- complete
ComBat_CPTAC_list2 <- ComBat_CPTAC_list
ComBat_CPTAC_list2[["Original"]] <- do.combat.sim(complete, pdat, cov=F)
CPTAC_list3 <- lapply(CPTAC_list2, function(x) x[which(!grepl("HUMAN", rownames(x))),])
ComBat_CPTAC_list3 <- lapply(ComBat_CPTAC_list2, function(x) x[which(!grepl("HUMAN", rownames(x))),])
#### Perform PCA on data
CPTAC_PCA = lapply(CPTAC_list3, function(x) prcomp(t(x), scale.=T, center=T))
ComBat_CPTAC_PCA = lapply(ComBat_CPTAC_list3, function(x) prcomp(t(x), scale.=T, center=T))


temp_list = as.list(c("Original","KNN","MinProb","Mean","SVD"))
plot_CPTAC_PCA <- lapply(temp_list, function(res){
  out = CPTAC_PCA[[res]]$x[,1:2] %>% as.data.frame() %>% mutate(., Group=factor(res, levels=c("Original","KNN","Mean","MinProb","SVD")), Batch=as.factor(batch_factor), Class=as.factor(class_factor), bec="Uncorrected")
  return(out)
  }) %>% do.call("rbind", .)
plot_CPTAC_PCA$Group = plyr::revalue(plot_CPTAC_PCA$Group, c("Original" = "MVs Removed"))
plot_ComBat_CPTAC_PCA <- lapply(temp_list, function(res){
  out = ComBat_CPTAC_PCA[[res]]$x[,1:2] %>% as.data.frame() %>% mutate(., Group=factor(res, levels=c("Original","KNN","Mean","MinProb","SVD")), Batch=as.factor(batch_factor), Class=as.factor(class_factor), bec="Corrected")
  return(out)
  }) %>% do.call("rbind", .)
plot_ComBat_CPTAC_PCA$Group = plyr::revalue(plot_ComBat_CPTAC_PCA$Group, c("Original" = "MVs Removed"))

plot_both_pca_cptac <- rbind(plot_CPTAC_PCA, plot_ComBat_CPTAC_PCA) %>% mutate(., bec=factor(.$bec,levels=c("Uncorrected","Corrected")))

ggplot(plot_both_pca_cptac, aes(x=PC1, y=PC2, fill=Batch, shape=Class)) + geom_point(size=3) + facet_grid(bec~Group) + labs(title="(A) CPTAC dataset") + theme(legend.position = "bottom", strip.text = element_text(size=12, margin=margin(t=1,b=1), face="bold"), title=element_text(face="bold"), axis.text = element_text(face="bold")) + scale_shape_manual(values=c(21:25)) + guides(fill = guide_legend(override.aes = list(shape=21), order=1))
```

Subset the CPTAC data matrix feature-wise by 3 levels of BEAMs severity
```{r}
# Discovered by one batch only
by1 = check_beams(cptac_df, pdat$class, pdat$batch)
by1_df = cptac_df[by1,]
# Missing in at least one batch
ms_by1 = check_beams(cptac_df, pdat$class, pdat$batch, by_single_batch = F)
ms_by1_only = ms_by1
ms_by1_only[by1 == TRUE] = FALSE
ms_by1_only_df = cptac_df[ms_by1_only,]
# Normal missingness
ms_df = cptac_df[ms_by1==FALSE,]


#### Extract Features from each category
# Discovered by one batch only
imp_by1_df = lapply(CPTAC_list[2:5], function(x) x[by1,])
bc_imp_by1_df = lapply(ComBat_CPTAC_list, function(x) x[by1,])

# Missing in at least one batch
imp_ms_by1_only_df = lapply(CPTAC_list[2:5], function(x) x[ms_by1_only,])
bc_imp_ms_by1_only_df = lapply(ComBat_CPTAC_list, function(x) x[ms_by1_only,])

# Normal missingness
imp_ms_df = lapply(CPTAC_list[2:5], function(x) x[ms_by1==FALSE,])
bc_imp_ms_df = lapply(ComBat_CPTAC_list, function(x) x[ms_by1==FALSE,])

#### Remove differential features
diff_by1=which(grepl("HUMAN", rownames(imp_by1_df[[1]])))
diff_ms_by1=which(grepl("HUMAN", rownames(imp_ms_by1_only_df[[1]])))
diff_ms=which(grepl("HUMAN", rownames(imp_ms_df[[1]])))

###### Remove differential proteins for fairer comparison
if (length(diff_by1) > 0){
  diff_removed_by1 = lapply(imp_by1_df, function(x) x[-diff_by1,])
  bc_diff_removed_by1 = lapply(bc_imp_by1_df, function(x) x[-diff_by1,])
} else {
  diff_removed_by1 = imp_by1_df
  bc_diff_removed_by1 = bc_imp_by1_df
}
if (length(diff_ms_by1) > 0){
  diff_removed_ms_by1 = lapply(imp_ms_by1_only_df, function(x) x[-diff_ms_by1,])
  bc_diff_removed_ms_by1 = lapply(bc_imp_ms_by1_only_df, function(x) x[-diff_ms_by1,])
} else {
  diff_removed_ms_by1 = imp_ms_by1_only_df
  bc_diff_removed_ms_by1 = bc_imp_ms_by1_only_df
}
if (length(diff_ms) > 0){
  diff_removed_ms = lapply(imp_ms_df, function(x) x[-diff_ms,])
  bc_diff_removed_ms = lapply(bc_imp_ms_df, function(x) x[-diff_ms,])
} else {
  diff_removed_ms = imp_ms_df
  bc_diff_removed_ms = bc_imp_ms_df
}

###### find subset with fewest features
subset_features=c(nrow(diff_removed_by1[[1]]), nrow(diff_removed_ms_by1[[1]]), nrow(diff_removed_ms[[1]]))
fewest_features_subset=which(subset_features == min(subset_features))

ind1 = sample(x=seq(subset_features[1]),
              size=subset_features[fewest_features_subset],
              replace=FALSE)
ind2 = sample(x=seq(subset_features[2]),
              size=subset_features[fewest_features_subset],
              replace=FALSE)
ind3 = sample(x=seq(subset_features[3]),
              size=subset_features[fewest_features_subset],
              replace=FALSE)
sampled_by1 = lapply(diff_removed_by1, function(x) x[ind1,])
sampled_ms_by1 = lapply(diff_removed_ms_by1, function(x) x[ind2,])
sampled_ms = lapply(diff_removed_ms, function(x) x[ind3,])
bc_sampled_by1 = lapply(bc_diff_removed_by1, function(x) x[ind1,])
bc_sampled_ms_by1 = lapply(bc_diff_removed_ms_by1, function(x) x[ind2,])
bc_sampled_ms = lapply(bc_diff_removed_ms, function(x) x[ind3,])
```


Correlation heatmaps
```{r, fig.height = 8, fig.width = 12}
###### Correlation heatmap
anno<-data.frame(row.names=colnames(cptac_df), Batch=paste0("Batch_",batch_factor), Class=paste0("Class_",class_factor))
annoCol<-list(Batch=c(Batch_1="blue", Batch_2="red", Batch_3="orange", Batch_4="grey", Batch_5="purple1", Batch_6="black", Batch_7="yellow", Batch_8="pink", Batch_9="magenta", Batch_10="darkgreen"),
              Class=c(Class_1="green2", Class_2="cyan", Class_3="purple", Class_4="black", Class_5="yellow"))

helper_list <- as.list(1:4)
label_names <- c("KNN","MinProb","Mean","SVD")
corheatmaps <- lapply(helper_list, function(x){
  cor_mat = cor(na.omit(sampled_by1[[x]]), method='pearson', use='complete.obs')
  h1=pheatmap(cor_mat, cluster_rows = T,cluster_cols = T, color=blues9, main="",
           show_colnames = F, show_rownames = F, annotation_col = anno, annotation_colors = annoCol,
           annotation_legend = F, silent = T, treeheight_row = 0) %>% as.ggplot()
  cor_mat = cor(na.omit(sampled_ms_by1[[x]]), method='pearson', use='complete.obs')
  h2=pheatmap(cor_mat, cluster_rows = T,cluster_cols = T, color=blues9, main="",
           show_colnames = F, show_rownames = F, annotation_col = anno, annotation_colors = annoCol,
           annotation_legend = F, silent = T, treeheight_row = 0) %>% as.ggplot()
  cor_mat = cor(na.omit(sampled_ms[[x]]), method='pearson', use='complete.obs')
  h3=pheatmap(cor_mat, cluster_rows = T,cluster_cols = T, color=blues9, main="",
           show_colnames = F, show_rownames = F, annotation_col = anno, annotation_colors = annoCol,
           annotation_legend = F, silent = T, treeheight_row = 0) %>% as.ggplot()
  
  # Corrected
  cor_mat = cor(na.omit(bc_sampled_by1[[x]]), method='pearson', use='complete.obs')
  h4=pheatmap(cor_mat, cluster_rows = T,cluster_cols = T, color=blues9, main="",
           show_colnames = F, show_rownames = F, annotation_col = anno, annotation_colors = annoCol,
           annotation_legend = F, silent = T, treeheight_row = 0) %>% as.ggplot()
  cor_mat = cor(na.omit(bc_sampled_ms_by1[[x]]), method='pearson', use='complete.obs')
  h5=pheatmap(cor_mat, cluster_rows = T,cluster_cols = T, color=blues9, main="",
           show_colnames = F, show_rownames = F, annotation_col = anno, annotation_colors = annoCol,
           annotation_legend = F, silent = T, treeheight_row = 0) %>% as.ggplot()
  cor_mat = cor(na.omit(bc_sampled_ms[[x]]), method='pearson', use='complete.obs')
  h6=pheatmap(cor_mat, cluster_rows = T,cluster_cols = T, color=blues9, main="",
          show_colnames = F, show_rownames = F, annotation_col = anno, annotation_colors = annoCol,
           annotation_legend = F, silent = T, treeheight_row = 0) %>% as.ggplot()
  out_plot = ggarrange(h3,h2,h1,h6,h5,h4, common.legend=T, legend="bottom")

  # Create title
  text_grob <- text_grob(label = label_names[x], 
                       face = "bold", 
                       size = 16, 
                       hjust = 0.5)
  out_plot <- annotate_figure(out_plot, top = text_grob)
})

for (i in 1:4){
  print(corheatmaps[[i]])
}
```

Session info
```{r}
sessionInfo()
```
